FROM node:lts-alpine AS alpine
ENV NODE_ENV development

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json .

#Iinstall only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install
# Copy the contents of the project to the image
COPY . .

# Validate typescript installation (use npx to run local binary)
RUN npx tsc --version

# Run 'npm start' when the container starts.
CMD ["npm", "run", "start"]