version: '3.9'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - node_modules:/app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
volumes:
  node_modules:
    name: node_modules